### ISSUE TITLE
Cannot upload document with version 2.3.0 and up

### ISSUE THREAD

**Issue by nextlevelbeard** [onfido/onfido-node#74]
The following code is working with version `2.2.0` but not `2.3.0`

```ts
const onfido = new Onfido({
  apiToken: process.env.ONFIDO_TOKEN ?? '',
  region: Region.EU
});

await onfido.document.upload({
  // Previously created applicant
  applicantId: documentApplicantId, 
  // https://documentation.onfido.com/images/sample_driving_licence.png
  file: fs.createReadStream(sampleLicense), 
  type: 'driving_licence',
  side: 'front'
});
```

Logs:
```js
TypeError: source.on is not a function
    at Function.DelayedStream.create (/Users/[REDACTED]/repos/[REDACTED]/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/Users/[REDACTED]/repos/[REDACTED]/node_modules/combined-stream/lib/combined_stream.js:45:37)
    at FormData.append (/Users/[REDACTED]/repos/[REDACTED]/node_modules/@onfido/api/node_modules/form-data/lib/form_data.js:74:3)
    at /Users/[REDACTED]/repos/[REDACTED]/node_modules/@onfido/api/src/formatting.ts:58:20
    at Array.reduce (<anonymous>)
    at toFormData (/Users/[REDACTED]/repos/[REDACTED]/node_modules/@onfido/api/src/formatting.ts:51:33)
    at Documents.upload (/Users/[REDACTED]/repos/[REDACTED]/node_modules/@onfido/api/src/Resource.ts:100:22)
    at Documents.upload (/Users/[REDACTED]/repos/[REDACTED]/node_modules/@onfido/api/src/resources/Documents.ts:37:18)
```

**Comment by DavidMealha** [comment]
Hello @nextlevelbeard, I have tried to reproduce but couldn't. What type are you passing as `applicantId`?

I have tried the following:
```
const onfido = new Onfido({
    apiToken: "API_TOKEN",
    region: Region.EU
  });

  const applicant = await onfido.applicant.create({
    firstName: "Jane",
    lastName: "Doe",
    dob: "1990-01-01",
    address: {
      buildingNumber: "100",
      street: "Second Street",
      town: "London",
      postcode: "S2 2DF",
      country: "GBR"
    },
    location: {
      ipAddress: "127.0.0.1",
      countryOfResidence: "PRT"
    }
  });

  console.log(applicant);

  const document = await onfido.document.upload({
    applicantId: applicant.id,
    file: fs.createReadStream("/[PATH_TO_FILE]/sample_driving_licence.png"),
    type: "driving_licence",
    side: "front"
  });

console.log(document);
```

**Comment by nextlevelbeard** [comment]
Hey @DavidMealha, obrigado🇵🇹 for looking into this.
Good news is I seem to have solved my problem by changing the way I call `upload`.

From this:
 ```ts
await onfido.document.upload({
  // Previously created applicant
  applicantId: documentApplicantId, 
  // https://documentation.onfido.com/images/sample_driving_licence.png
  file: fs.createReadStream(sampleLicense), 
  type: 'driving_licence',
  side: 'front'
});
```
To this:
```ts
await onfido.document.upload({
  applicantId: documentApplicantId,
  file: {
    contents: fs.createReadStream(sampleLicense),
    filepath: sampleLicense,
    contentType: 'image/png'
  },
  type: 'driving_licence',
  side: 'front'
});
```

Hopefully that helps someone.
